// <auto-generated />
using System;
using Infraestructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Carrito", b =>
                {
                    b.Property<Guid>("CarritoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("CarritoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Carrito", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CarritoProducto", b =>
                {
                    b.Property<Guid>("CarritoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.HasKey("CarritoId", "ProductoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("CarritoProducto", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("DNI");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("ClienteId");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.HasIndex("Telefono")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Cliente", (string)null);

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Apellido = "Carrizo",
                            Direccion = "calle siempreviva 599",
                            Dni = "41389372",
                            Mail = "mariano.carrizo4280@gmail.com",
                            Nombre = "Mariano",
                            Password = "42804254M@c!",
                            Telefono = "1126824939",
                            UserName = "myuubi"
                        },
                        new
                        {
                            ClienteId = 2,
                            Apellido = "Veliz",
                            Direccion = "calle siempreviva 599",
                            Dni = "41354119",
                            Mail = "warlockphantasy@gmail.com",
                            Nombre = "Celeste",
                            Password = "42804254M@c!",
                            Telefono = "1513616310",
                            UserName = "celenya"
                        },
                        new
                        {
                            ClienteId = 3,
                            Apellido = "simpson",
                            Direccion = "calle siempreviva 599",
                            Dni = "31354119",
                            Mail = "donbarredora@gmail.com",
                            Nombre = "homero",
                            Password = "mmmCerveza!",
                            Telefono = "1513616317",
                            UserName = "donbarredora"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Orden", b =>
                {
                    b.Property<Guid>("OrdenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarritoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("OrdenId");

                    b.HasIndex("CarritoId")
                        .IsUnique();

                    b.ToTable("Orden", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"), 1L, 1);

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("ProductoId");

                    b.ToTable("Producto", (string)null);

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Categoria = "Almacen",
                            Codigo = "12956",
                            Descripcion = "Lata de tomate de 600g",
                            Image = "https://i.imgur.com/gqJVlWk.jpg",
                            Marca = "Marolio",
                            Nombre = "Lata de Tomate",
                            Precio = 800m
                        },
                        new
                        {
                            ProductoId = 2,
                            Categoria = "Almacen",
                            Codigo = "77734",
                            Descripcion = "lata de Arvejas de 600g",
                            Image = "https://i.imgur.com/AARTUJY.jpg",
                            Marca = "marolio",
                            Nombre = "Lata de Arvejas",
                            Precio = 1000m
                        },
                        new
                        {
                            ProductoId = 3,
                            Categoria = "Almacen",
                            Codigo = "67413",
                            Descripcion = "Fideos",
                            Image = "https://i.imgur.com/HNZyMIF.jpg",
                            Marca = "Marolio",
                            Nombre = "Fideos Tirabuzon",
                            Precio = 1700m
                        },
                        new
                        {
                            ProductoId = 4,
                            Categoria = "Almacen",
                            Codigo = "12956",
                            Descripcion = "500c",
                            Image = "https://i.imgur.com/lUrXZUw.jpg",
                            Marca = "Brahma",
                            Nombre = "Cerveza  Lata ",
                            Precio = 1500m
                        },
                        new
                        {
                            ProductoId = 5,
                            Categoria = "Almacen",
                            Codigo = "01756",
                            Descripcion = "botella de agua con gas 500ccc",
                            Image = "https://i.imgur.com/CfHIPke.jpg",
                            Marca = "Villavicencio",
                            Nombre = "botellla de agua con gas 500cc ",
                            Precio = 800m
                        },
                        new
                        {
                            ProductoId = 6,
                            Categoria = "Almacen",
                            Codigo = "00056",
                            Descripcion = "estuche de 4 unidades",
                            Image = "https://i.imgur.com/doMqjA2.jpg",
                            Marca = "Champion",
                            Nombre = "Hamburgesa",
                            Precio = 3500m
                        },
                        new
                        {
                            ProductoId = 7,
                            Categoria = "Almacen",
                            Codigo = "00001",
                            Descripcion = "arroz '0000' 500gr",
                            Image = "https://i.imgur.com/k5enq60.jpg",
                            Marca = "El Dique",
                            Nombre = "arroz",
                            Precio = 800m
                        },
                        new
                        {
                            ProductoId = 8,
                            Categoria = "Almacen",
                            Codigo = "00050",
                            Descripcion = "Aceite mezcla 900cc",
                            Image = "https://i.imgur.com/YZJQGpC.jpg",
                            Marca = "Marolio",
                            Nombre = "Aceite",
                            Precio = 1500m
                        },
                        new
                        {
                            ProductoId = 9,
                            Categoria = "Almacen",
                            Codigo = "03561",
                            Descripcion = "cacao en polvo 180gr",
                            Image = "https://i.imgur.com/eAFHPvX.jpg",
                            Marca = "Marolio",
                            Nombre = "Cacao en polvo",
                            Precio = 1200m
                        },
                        new
                        {
                            ProductoId = 10,
                            Categoria = "Almacen",
                            Codigo = "09993",
                            Descripcion = "queso rallado 100Gr",
                            Image = "https://i.imgur.com/jaFvFal.jpg",
                            Marca = "Gikar",
                            Nombre = "Queso Rallado",
                            Precio = 300m
                        },
                        new
                        {
                            ProductoId = 11,
                            Categoria = "Limpieza",
                            Codigo = "09995",
                            Descripcion = "Desinfectante de Superficies 380ml",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791290795754.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Cif",
                            Nombre = "Limpiador Líquido",
                            Precio = 2634m
                        },
                        new
                        {
                            ProductoId = 12,
                            Categoria = "Limpieza",
                            Codigo = "09970",
                            Descripcion = "Aerosol Desinfectante de Ambientes y Superficies 360cm3",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791290795778.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Cif",
                            Nombre = "Aerosol Desinfectante de Ambientes y Superficies",
                            Precio = 3631m
                        },
                        new
                        {
                            ProductoId = 13,
                            Categoria = "Limpieza",
                            Codigo = "09971",
                            Descripcion = "Limpiador Desinfectante de Superficies 250ml",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791290795808.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Cif",
                            Nombre = "Limpiador Desinfectante de Superficies Cif Gel",
                            Precio = 3631m
                        },
                        new
                        {
                            ProductoId = 14,
                            Categoria = "Limpieza",
                            Codigo = "09972",
                            Descripcion = "Limpiador Desinfectante Para Pisos 750ml",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791290795815.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Cif",
                            Nombre = "Limpiador Desinfectante Para Pisos",
                            Precio = 3634m
                        },
                        new
                        {
                            ProductoId = 15,
                            Categoria = "Limpieza",
                            Codigo = "09973",
                            Descripcion = "Pala Click Plastica Residuos",
                            Image = "https://clubdebeneficios.com/media/catalog/product/p/a/palaclick.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Virulana",
                            Nombre = "Pala Click Plastica",
                            Precio = 4620m
                        },
                        new
                        {
                            ProductoId = 16,
                            Categoria = "Limpieza",
                            Codigo = "09974",
                            Descripcion = "Con Espuma Y Secador",
                            Image = "https://clubdebeneficios.com/media/catalog/product/n/o/noso0964.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Virulana",
                            Nombre = "Limpiavidrios",
                            Precio = 4634m
                        },
                        new
                        {
                            ProductoId = 17,
                            Categoria = "Limpieza",
                            Codigo = "09975",
                            Descripcion = "esponja de bronce 16gr",
                            Image = "https://clubdebeneficios.com/media/catalog/product/b/r/bronce_alta_ean_7794440002238.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Virulana",
                            Nombre = "Virulana Bronce",
                            Precio = 800m
                        },
                        new
                        {
                            ProductoId = 18,
                            Categoria = "Limpieza",
                            Codigo = "09976",
                            Descripcion = "rollitos 70gr",
                            Image = "https://clubdebeneficios.com/media/catalog/product/r/o/rollitosx10_alta_ean_7794440101702.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Virulana",
                            Nombre = "Virulana Rollitos X 10",
                            Precio = 1400m
                        },
                        new
                        {
                            ProductoId = 19,
                            Categoria = "Limpieza",
                            Codigo = "09977",
                            Descripcion = "Vim Citrus 700ml",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791290794979.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Vim",
                            Nombre = "Lavandina en Gel",
                            Precio = 1900m
                        },
                        new
                        {
                            ProductoId = 20,
                            Categoria = "Limpieza",
                            Codigo = "09978",
                            Descripcion = "pino 100gr",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791290794153.h.png?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Vim",
                            Nombre = "Pastilla Para Inodoro",
                            Precio = 1600m
                        },
                        new
                        {
                            ProductoId = 21,
                            Categoria = "Limpieza",
                            Codigo = "09979",
                            Descripcion = "Desengrasante 1kg",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791290792470.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Sun",
                            Nombre = "Polvo para máquinas Lavavajilla",
                            Precio = 1300m
                        },
                        new
                        {
                            ProductoId = 22,
                            Categoria = "Perfumeria",
                            Codigo = "09980",
                            Descripcion = "Afeitadora Soleil Clic Sensitive 50gr",
                            Image = "https://clubdebeneficios.com/media/catalog/product/m/o/mockup_soleil_clic_sensitive_bl5_2022_frente.png?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Bic",
                            Nombre = "Afeitadora Soleil Clic Sensitive",
                            Precio = 5600m
                        },
                        new
                        {
                            ProductoId = 23,
                            Categoria = "Perfumeria",
                            Codigo = "09981",
                            Descripcion = "Afeitadora Flex 3 Hybrid 45gr",
                            Image = "https://clubdebeneficios.com/media/catalog/product/9/6/968722_flex3_hybrid_5un.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Bic",
                            Nombre = "Afeitadora Flex 3 Hybrid",
                            Precio = 4500m
                        },
                        new
                        {
                            ProductoId = 24,
                            Categoria = "Perfumeria",
                            Codigo = "09982",
                            Descripcion = "Sérum Corporal Dove Pro-Retinol 400ml",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/5/7506306252882_1_1.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Dove",
                            Nombre = "Sérum Corporal Dove Pro-Retinol",
                            Precio = 5600m
                        },
                        new
                        {
                            ProductoId = 25,
                            Categoria = "Perfumeria",
                            Codigo = "09983",
                            Descripcion = "Sérum Corporal Dove Niacinamida 400ml",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/5/7506306252875_1_1.jpg?quality=80&fit=bounds&height=700&width=700&canvas=700:700",
                            Marca = "Dove",
                            Nombre = "Sérum Corporal Dove Niacinamida",
                            Precio = 3600m
                        },
                        new
                        {
                            ProductoId = 26,
                            Categoria = "Perfumeria",
                            Codigo = "09984",
                            Descripcion = "Sérum Corporal Dove Pro-Ceramidas 400ml",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/5/7506306252868_1_1.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Dove",
                            Nombre = "Sérum Corporal Dove Pro-Ceramidas",
                            Precio = 3600m
                        },
                        new
                        {
                            ProductoId = 27,
                            Categoria = "Perfumeria",
                            Codigo = "09985",
                            Descripcion = "Antitranspirante Dove Men+Care Extra fresh Roll-On 50ml",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/8/78925519.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Dove",
                            Nombre = "Antitranspirante Dove Men+Care Extra fresh Roll-On",
                            Precio = 3500m
                        },
                        new
                        {
                            ProductoId = 28,
                            Categoria = "Perfumeria",
                            Codigo = "09986",
                            Descripcion = "Desodorante Aerosol Axe BZRP 150ml",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791293051031_1_6.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Axe",
                            Nombre = "Desodorante Aerosol Axe BZRP",
                            Precio = 2100m
                        },
                        new
                        {
                            ProductoId = 29,
                            Categoria = "Perfumeria",
                            Codigo = "09987",
                            Descripcion = "Multipack 90gr",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/8/7891150095700_1.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Dove",
                            Nombre = "Jabón en Barra Dove Piel Sensible x3",
                            Precio = 2300m
                        },
                        new
                        {
                            ProductoId = 30,
                            Categoria = "Perfumeria",
                            Codigo = "09988",
                            Descripcion = "Jabón Liquido para manos Lux Botanicals Orquídea Negra 250ml",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791293048833_1_1.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Lux",
                            Nombre = "Jabón Liquido para manos Lux Botanicals Orquídea Negra",
                            Precio = 2500m
                        },
                        new
                        {
                            ProductoId = 31,
                            Categoria = "Perfumeria",
                            Codigo = "09989",
                            Descripcion = "Multipack 120gr",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791293050959.h_1.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Rexona",
                            Nombre = "Jabón en Barra Rexona Nutritive Orchid x3",
                            Precio = 2300m
                        },
                        new
                        {
                            ProductoId = 32,
                            Categoria = "Perfumeria",
                            Codigo = "09990",
                            Descripcion = "Multipack 120gr",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791293050935.h.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Rexona",
                            Nombre = "Jabón en Barra Rexona Cotton Fresh x3",
                            Precio = 2300m
                        },
                        new
                        {
                            ProductoId = 33,
                            Categoria = "CuidadoRopa",
                            Codigo = "09991",
                            Descripcion = "Suavizante Concentrado Comfort Energia Floral 1lt",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791290795952.jpg?quality=80&fit=bounds&height=700&width=700&canvas=700:700",
                            Marca = "Comfort",
                            Nombre = "Suavizante Concentrado Comfort Energia Floral 1lt",
                            Precio = 6555m
                        },
                        new
                        {
                            ProductoId = 6479,
                            Categoria = "Cuidado de ropa",
                            Codigo = "09992",
                            Descripcion = "Suavizante Concentrado Comfort Energia Floral 500ml",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/8/7891150025288.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Comfort",
                            Nombre = "Suavizante Concentrado Comfort Energia Floral 500ml",
                            Precio = 50m
                        },
                        new
                        {
                            ProductoId = 35,
                            Categoria = "Cuidado de ropa",
                            Codigo = "09993",
                            Descripcion = "Jabón Líquido Concentrado para Diluir Ala con Bicarbonato 500ml",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791290795495.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Ala",
                            Nombre = "Jabón Líquido Concentrado para Diluir Ala con Bicarbonato 500ml",
                            Precio = 6479m
                        },
                        new
                        {
                            ProductoId = 36,
                            Categoria = "Cuidado de ropa",
                            Codigo = "09960",
                            Descripcion = "Jabón Líquido Concentrado para Diluir Skip Power Deluxe 500ml",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791290795518.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Skip",
                            Nombre = "Jabón Líquido Concentrado para Diluir Skip Power Deluxe 500ml",
                            Precio = 30479m
                        },
                        new
                        {
                            ProductoId = 37,
                            Categoria = "Cuidado de ropa",
                            Codigo = "09961",
                            Descripcion = "Jabón Líquido Concentrado para Diluir Skip Power Oxi 500ml",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791290795501.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Skip",
                            Nombre = "Jabón Líquido Concentrado para Diluir Skip Power Oxi 500ml",
                            Precio = 30479m
                        },
                        new
                        {
                            ProductoId = 38,
                            Categoria = "Cuidado de ropa",
                            Codigo = "09962",
                            Descripcion = "Suavizante para ropa Vivere Explosión Floral Clásico DP 3L",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791290793743_1.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Vivere",
                            Nombre = "Suavizante para ropa Vivere Explosión Floral Clásico DP 3L",
                            Precio = 15000m
                        },
                        new
                        {
                            ProductoId = 39,
                            Categoria = "Cuidado de ropa",
                            Codigo = "09963",
                            Descripcion = "Suavizantes para ropa Vivere Explosión Floral Plancha Fácil 810 ml",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791290793774.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Vivere",
                            Nombre = "Suavizantes para ropa Vivere Explosión Floral Plancha Fácil 810 ml",
                            Precio = 6418m
                        },
                        new
                        {
                            ProductoId = 40,
                            Categoria = "Cuidado de ropa",
                            Codigo = "09964",
                            Descripcion = "Saltar al comienzo de la galería de imágenes\r\nSuavizante para ropa Vivere Explosión Floral Clásico 3 lt",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791290793866_1.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Vivere",
                            Nombre = "Suavizante para ropa Vivere Explosión Floral Clásico 3 lt",
                            Precio = 8418m
                        },
                        new
                        {
                            ProductoId = 41,
                            Categoria = "Cuidado de ropa",
                            Codigo = "09965",
                            Descripcion = "Suavizante Concentrado Comfort Frescor Intenso 500 ml",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/8/7891150000971_2.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Comfort",
                            Nombre = "Suavizante Concentrado Comfort Frescor Intenso 500 ml",
                            Precio = 4959m
                        },
                        new
                        {
                            ProductoId = 42,
                            Categoria = "Cuidado de ropa",
                            Codigo = "09966",
                            Descripcion = "Suavizante Regular Comfort Clásico Bidón 5lt",
                            Image = "https://clubdebeneficios.com/media/catalog/product/7/7/7791290793705.h.jpg?quality=80&fit=bounds&height=&width=&canvas=:",
                            Marca = "Comfort",
                            Nombre = "Suavizante Regular Comfort Clásico Bidón 5lt",
                            Precio = 10845m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Carrito", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Cliente")
                        .WithMany("Carritos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Domain.Entities.CarritoProducto", b =>
                {
                    b.HasOne("Domain.Entities.Carrito", "Carrito")
                        .WithMany("CarritoProductos")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Producto", "Producto")
                        .WithMany("CarritoProductos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Domain.Entities.Orden", b =>
                {
                    b.HasOne("Domain.Entities.Carrito", "Carrito")
                        .WithOne("Orden")
                        .HasForeignKey("Domain.Entities.Orden", "CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");
                });

            modelBuilder.Entity("Domain.Entities.Carrito", b =>
                {
                    b.Navigation("CarritoProductos");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Carritos");
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.Navigation("CarritoProductos");
                });
#pragma warning restore 612, 618
        }
    }
}
